config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :galleries
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar

  has_many :galleries, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @user = User.find(params[:user_id])
    @galleries = @user.galleries.with_attached_photos
    puts @galleries
  end

  def show
    @gallery = Gallery.find(params[:id])
    @images = @gallery.images
  end

  def new
    @user = User.find(params[:user_id])
    @gallery = Gallery.new
  end

  def create
    @user = User.find(params[:user_id])
    @gallery = @user.galleries.new(gallery_params)

    if @gallery.save
      redirect_to @user
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @gallery = Gallery.find(params[:id])

    if @gallery.destroy
      redirect_to galleries_path
    else
      render :show, status: :unprocessable_entity
    end
  end

  def gallery_params
    params.require(:gallery).permit(:title, :user_id, photos:[])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])

    if @user.destroy
      redirect_to users_path
    else
      render :show, status: :unprocessable_entity
    end
  end

  def user_params
    params.require(:user).permit(:name, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/galleries/_gallery.html.erb
<h1><%= gallery.title %></h1>

<% gallery.photos.each do |photo| %>
  <%= image_tag photo, style: "width:100px;" %>
<% end %>

app/views/galleries/index.html.erb
<h1>Galleries (<%= @galleries.count %>)</h1>
<% @galleries.each do |gallery| %>
  <%= render gallery %>
<% end %>

<%= link_to "New gallery", new_user_gallery_path %>

app/views/galleries/new.html.erb
<h1> New gallery </h1>
<%= form_with model: [ @user, @user.galleries.build ] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.file_field :photos, multiple: true %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FileManagerTurboRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= link_to "Back to users", users_path %>
    <%= yield %>
  </body>
</html>

app/views/users/_user.html.erb
<div style="display:flex; border: 1px solid black; gap: 4px;border-radius: 10px;align-items:center;">
  <h1><%= user.name %></h1>
  <%= image_tag user.avatar, style: 'width: 50px; height: 50px;' %>
</div>

app/views/users/index.html.erb
<h1>Users (<%= @users.count %>)</h1>
<% @users.each do |user| %>
	<div style="display: flex; gap: 10px;">
		<%= render user %>
		<%= link_to "Show", user_path(user) %>
		<%= link_to "Galleries", user_galleries_path(user) %>
		<%= button_to "Delete", user, :method => :delete %>
	</div>
<% end %>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1> New User </h1>
<%= form_with model: @user do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.file_field :avatar %>
	
	<%= f.submit %>
<% end %>

app/views/users/show.html.erb
<%= render @user %>